### ISSUE TITLE
LoadError 

### ISSUE THREAD

**Issue by abhisheksingh23** [yatish27/linkedin-scraper#78]
I installed linkedin-scraper and tried to include it in my script . I get the following load error . 

 >LoadError: cannot load such file -- linkedin-scraper
>from /home/abhi/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>from /home/abhi/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>from (irb):3
from /home/abhi/.rbenv/versions/2.1.5/bin/irb:11:in `<main>'

**Comment by abhisheksingh23** [comment]
My Ruby version is 'ruby 2.1.5p273' I guess the gem is not tested for this particular environment .

**Comment by abhisheksingh23** [comment]
Problem solved after require 'linkedin_scraper'(will save a lot of time for others ) . 
Please merge pull request for the documentation.
https://github.com/yatish27/linkedin-scraper/pull/79
